# promise

学习 Promise 之前我们需要了解 回调地狱

**多层回调函数的相互嵌套，就形成了回调地狱。**

回调地狱的缺点：

- 代码耦合性太强，牵一发而动全身，难以维护；
- 大量冗余的代码相互嵌套，代码的可读性变差；

---

**Promise 是异步编程的一种优雅的解决方案**，是一个构造函数，有all、reject、resolve这几个方法，原型上有then、catch等方法

## Promise 特点

（1）Promise对象里的异步操作执行时**有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败)** , 而Promise对象状态的改变，只有两种可能：**从pending变为fulfilled或者从pending变为rejected。**

（2）而一旦上面的这种状态发生改变，之后就不会再变，任何时候都可以得到这个结果。**如果改变已经发生了，你再对Promise对象添加回调函数，也会立即得到这个结果**。

（3） Promise.prototype 上包含一个 `.then()` 方法	**每一次 new Promise() 构造函数得到的实例对象，都可以通过原型链的方式访问到 .then() 方法**, `.then()` 方法用来预先指定成功和失败的回调函数, 也可以 p.then(result => { }, error => { })；这样的方式, 调用 .then() 方法时，成功的回调函数是必选的、失败的回调函数是可选的；

（4）**new 出来的 Promise 实例对象，里面存放一个异步操作；**

以下案例均在 vue 的代码中演示

```js
  mounted() {
    let promise1 = new Promise(function(resolve, reject){
      //做一些异步操作 ( 可以是网络请求,定时器,回调函数,事件绑定 )
      setTimeout(function(){
        console.log('完成异步操作');
        resolve('返回任意的数据');
        // 会在两秒之后返回打印值
      }, 2000);
    })
  }
```

**这里我们 new 了一个 Promise , 在 Promise 里面执行异步操作的代码** 

可以看到,这里**只是对他进行了声明,并没有执行这一个函数**

但是从结果上看来结果 却是执行了 这个函数  ,  这里先忘记里面的  resolve('返回任意的数据') 里起了什么作用

**其执行过程是：执行了一个异步操作，也就是setTimeout，2秒后，输出“完成异步操作”，并且调用resolve方法。这里首先要明白一件事情, Promise 对象的声明会使内部的异步操作发生**

这里需要知道的是:  如果我们直接 new 一个 promise , 而没有将他放置在函数中的时候 , 他会直接执行里面的异步操作

所以我们用Promise的时候一般是包在一个函数中，在需要的时候去运行这个函数 , 这里演示一下

```js
  methods: {
    test:function () {
      return new Promise(function(resolve, reject){
        //做一些异步操作 ( 可以是网络请求,定时器,回调函数,事件绑定 )
        setTimeout(function(){
          console.log('完成异步操作');
          resolve('返回任意的数据');
          // 会在两秒之后返回打印值
        }, 2000);
      })
    }
  },
  mounted() {
    this.test()
  }
```

可以看到 在这里 我们直接 return 出  Promise对象 , 这将在在之后给我们非常大的便利 , **可以让我们直接链式调用它的方法**

##  resolve() 的作用

先看一段代码和结果

```js
mounted() {
  let promise = new Promise(function(resolve, reject){
    //做一些异步操作 ( 可以是网络请求,定时器,回调函数,事件绑定 )
    setTimeout(function(){
      resolve('返回任意的数据');
      // 会在两秒之后返回打印值
    }, 2000);
  }).then((data) => {
    console.log(data)
  })
}
```


我们可以发现在之后的 .then(data) 中有一句 console.log(data)

这这里的 **data 对应的正是 resolve() 参数中返回的值** , **原来then里面的函数就跟我们平时的回调函数一个意思，能够在这个异步任务执行完成之后被执行.** 而这也这就是Promise的作用了，**用链式调用的方式执行回调函数。**

而 Promise的优势正是在于可以链式调用 , 可以在then方法中继续写Promise对象并返回，然后继续调用then来进行回调操作。

但是 + - +

```js
  mounted() {
    return new Promise(function (resolve, reject) {
      if (1 < 2) {
        resolve(true)
      } else {
        console.log("error")
      }
    }).then((data) => {
      console.log(data)
      return new Promise(function (resolve, reject) {
        if (2 < 3) {
          resolve(true)
        } else {
          console.log("error")
        }
      })
    }).then((data) => {
      console.log(data)
      return new Promise(function (resolve, reject) {
        if (2 < 3) {
          resolve(true)
        } else {
          console.log("error")
        }
      }).then((data) => {
        console.log(data)
      })
    })
  }
```

上面这样子的代码  是不是很丑 , 很难看懂 + - + , 而且和之前的回调地狱一样不方便读懂代码

但是实际上 不这么搞

## 我们一般采用下面的写法

```js
  methods: {
    test:function () {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1);
        },1000)
      })
    }
  },
  mounted() {
    this.test()
        .then((data) => {
          console.log(data)
          // 返回 Promise 对象, 使其继续进行链式调用 
          return this.test()
        })
        .then((data) => {
          console.log(data)
          return this.test()
        })
        .then((data) => {
          console.log(data)
          return this.test()
        })
        .then((data) => {
          console.log(data)
        })
  }
```

这样就能够按顺序,输出每个异步回调中的内容

每次 .then 中的 return 都可以返回一个 Promise , 从而可以在之后继续链式调用  , 这样写是不是就很好看了


## reject() 的用法

**resolve是对promise成功执行时候的回调,它把promise的状态修改为fullfiled**

那么，**reject就是失败的时候的回调，他把promise的状态修改为rejected**，这样我们就可以在 .then中 捕捉到，然后执行“失败”情况的回调

```js
  methods: {
    test:function () {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1);
        },1000)
      })
    }
  },
  mounted() {
    this.test()
        .then((data) => {
          console.log(data)
          return this.test()
        })
        .then((data) => {
          console.log(data)
          return this.test()
        })
        .then((data) => {
          console.log(data)
          return this.test()
        })
        .then((data) => {
          console.log(data)
          return new Promise((resolve, reject) => {
            if ( 1 !== 1) {
              reject(1);
            } else {
              resolve(2);
            }
          })
        })
       .then((data) => {
         console.log(data)
       },(info) => {
         console.log(info)
       })
  }
```

这里在最后一次调用 promise 返回的结果时 , 执行力 resolve(2) , 最后打印台显示的结果也是 2 ,

而且我们也可以看到 , 在then中传了两个参数，这两个参数分别是两个函数，then方法可以接受两个参数，**第一个对应resolve的回调，第二个对应reject的回调。（也就是说then方法中接受两个回调，一个成功的回调函数，一个失败的回调函数）**，所以我们能够分别拿到成功和失败传过来的数据就有以上的运行结果

![在这里插入图片描述](https://img-blog.csdnimg.cn/b7cc3321da2348b981fdedfcf2bb6b3a.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBAeGltaW5neA==,size_20,color_FFFFFF,t_70,g_se,x_16)

接下来我们再看一下 .catch 和 直接在 .then 中传入第二个参数的区别

```js
methods: {
  test: function () {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(1);
      }, 1000)
    })
  }
},
mounted() {
  this.test()
      .then((data) => {
        console.log(data)
        return this.test()
      })
      .then((data) => {
        console.log(data)
        return this.test()
      })
      .then((data) => {
        console.log(data)
        return this.test()
      })
      .then((data) => {
        console.log(data)
        return new Promise((resolve, reject) => {
          if (1 !== 1) {
            reject(1);
          } else {
            resolve(2);
          }
        })
      })
      .then((data) => {
        console.log(data)
      })
      .catch((info) => {
        console.log(info)
      })
}
```

我们可以看到: 两次结果是一样的 , 但是我们需要明白 , 在 .then 中写第二个参数 和 用 .catch 是有区别的

.catch 除了会得到失败的结果,还会捕获异常 , 类似于一些语法的错误 , 在捕获到异常的时候 , 并不会卡死 , 而是继续执行下面的代码
**与then同级的另一个方法，all方法，该方法提供了并行执行异步操作的能力，并且在所有异步操作执行完后并且执行结果都是成功的时候才执行回调。**

##  all() 多个Promise 一起执行

参数需要使用一个数组来包含所有的包含 PromIse 的方法 

```js
  methods: {
    test1: function () {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1);
        }, 1000)
      })
    },
    test2: function () {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1);
        }, 1000)
      })
    },
    test3: function () {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1);
        }, 1000)
      })
    }
  },
  mounted() {
      // 用一个数组包括
    Promise.all([this.test1, this.test2, this.test3])
        .then((res) => {
          console.log(res)
          console.log(res.length)
        })
  }
```

这里在三个异步方法都执行完毕后 , 返回了一个数组 , 里面包含了每个方法对应的结果

![在这里插入图片描述](https://img-blog.csdnimg.cn/d48a26607ee24c4f942a96e9a45d7c4a.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBAeGltaW5neA==,size_20,color_FFFFFF,t_70,g_se,x_16)


Promise.all来执行多个异步操作，**all接收一个数组参数**，这组参数为需要执行异步操作的所有方法，**里面的值最终都算返回Promise对象。**

这样，**三个异步操作的并行执行的，等到它们都执行完后才会进到then里面**。

**数组中 Promise 实例的顺序，就是最终结果的顺序！**

## 除此之外还有 race 的 用法

all是等所有的异步操作都执行完了再执行then方法，那么race方法就是相反的，**谁先执行完成就先执行回调**。先执行完的不管是进行了race的成功回调还是失败回调，**其余的将不会再进入race的任何回调**

```js
methods: {
  test1: function () {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(1);
      }, 1000)
    })
  },
  test2: function () {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(1);
      }, 2000)
    })
  },
  test3: function () {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(1);
      }, 3000)
    })
  }
},
mounted() {
  Promise.race([this.test1, this.test2, this.test3])
      .then((res) => {
        console.log(res)
      })
}
```

这次只是 将 Promise.all 修改为了 Promise.race , 返回的结果中 只有最先执行结束的结果

![在这里插入图片描述](https://img-blog.csdnimg.cn/94290eb4a81246a988b7852feac0c76e.png)

**补充:**


```js
// Promise 用于解决回调地狱
// Promise 是一个构造函数
const fs = require('fs')
// 在 promise 容器 里的函数 里放置异步操作
// promise 容器一旦创建就开始执行里面的代码
new Promise(function (resolve, reject) {
  fs.readFile('./package.json', 'utf8', function (err, data) {
    if (err) {
     reject(err)
    } else {
      resolve(data)
    }
  })
}).then(data => {
  console.log(data);
  // -----------------------------------------------------------------------
  new Promise(function (resolve,reject) {
    fs.readFile('./package.json', 'utf8', function (err, data) {
      if (err) {
        reject(err)
      } else {
        resolve(data)
      }
    })
  }).then(data => {
    console.log(data);
  }).catch (err => {
    console.log(err);
  })
  // -----------------------------------------------------------------------
}).catch(err => {
  console.log(err);
})
```

**异步的处理方式**

```js
const fs = require("fs");

const p1 = new Promise((resolve, reject) => {
  fs.readFile('./a.txt', "utf8", (err, data) => {
    if (err) {
      reject(err)
    } else {
      resolve(data)
    }
  })
})

const p2 = new Promise((resolve, reject) => {
  fs.readFile('./b.txt', "utf8", (err, data) => {
    if (err) {
      reject(err)
    } else {
      resolve(data)
    }
  })
})

const p3 = new Promise((resolve, reject) => {
  fs.readFile('./c.txt', "utf8", (err, data) => {
    if (err) {
      reject(err)
    } else {
      resolve(data)
    }
  })
})

p1.then((data) => {
    console.log(data);
  // 这里的 return p2 会将 p2 的 resolve 结果 传递给下面的 .then
  // 当 return 一个 promise 对象时,后续的 .then 中方法的第一个参数会作为 返回的 promise (p2) 的 resolve
    return p2
})
  .catch((err) => {
    console.log(err);
  })
  .then(data => {
    console.log(data);
    return p3
  })
  .catch((err) => {
    console.log(err);
  })
  .then(data => {
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
  })
```

**异步函数的封装**

```js
const fs = require('fs')

function pReadFile(filePath) {
  return new Promise(function (resolve, reject) {
    fs.readFile(filePath, "utf8", function (err, data) {
      if (err) {
        reject(err)
      } else {
        resolve(data)
      }
    })
  })
}

pReadFile('./a.txt')
  .then(data => {
    console.log(data);
    return pReadFile('./b.txt')
  })
  .then((data) => {
    console.log(data);
    return pReadFile('./c.txt')
  })
  .then((data) => {
    console.log(data);
  })
```

**Promise 在创建后会立马执行**
下面代码中，Promise 新建后立即执行，所以首先输出的是Promise。然后，then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以resolved最后输出。
注意结果的输出顺序

```js
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('resolved.');
});

console.log('Hi!');

// Promise
// Hi!
// resolved
```

---

## 读取多个文件 (案例)

由于 node.js 官方提供的 fs 模块仅支持以回调函数的方式读取文件，不支持Promise 的调用方式。因此，需要先运行如下的命令，安装 `then-fs` 这个第三方包，从而支持我们基于 Promise 的方式读取文件的内容：

```bash
npm install then-fs
```

调用 then-fs 提供的 `readFile()` 方法，可以异步地读取文件的内容，它的返回值是 Promise 的实例对象。因此可以调用 `.then()` 方法为每个 Promise 异步操作指定成功和失败之后的回调函数。示例代码如下：

```js
import thenFS from 'then-fs'
thenFS.readFile("./1.text", "utf8").then(r1 => {
    console.log(r1)
})
thenFS.readFile("./1.text", "utf8").then(r2 => {
    console.log(r2)
})
thenFS.readFile("./1.text", "utf8").then(r3 => {
    console.log(r3)
})
```

上述的代码无法保证文件的读取顺序，需要做进一步的改进！

`Promise` 支持链式调用，从而来解决回调地狱的问题。示例代码如下：

```js
import thenFS from 'then-fs'
thenFS.readFile("./1.text", "utf8")
  .catch(err => {
    console.log(err)
})
  .then(r1 => {
    console.log(r1)
    return thenFS.readFile("./2.text", "utf8")
}).then(r2 => {
    console.log(r2)
    return thenFS.readFile("./3.text", "utf8")
}).then(r3 => {
    console.log(r3)
})
```



# async/await

**`async/await`** 是 **ES8（ECMAScript 2017）引入的新语法**，用来简化 Promise 异步操作。

在 `async/await` 出现之前，开发者只能通过链式.then() 的方式处理 Promise 异步操作。

而现在,`async/await` 的出现后, 一般我们都用await去等待一个async函数完成

不过按语法说明，await 等待的是一个表达式，这个表达式的计算结果是 Promise 对象或者其它值，所以，await后面实际可以接收普通函数调用或者直接量。

## async 关键字

先说一下async的用法，它作为一个关键字放到函数前面，**用于表示函数是一个异步函数**，因为async就是异步的意思， 异步函数也就意味着该函数的执行不会阻塞后面代码的执行。

1. **普通函数定义前加async关键字 普通函数变成异步函数**
2. **异步函数默认返回promise对象**
3. 在异步函数内部使用return关键字进行结果返回 结果会被包裹的promise对象中 return关键字代替了resolve方法
4. 在异步函数内部使用throw关键字抛出程序异常
5. 调用异步函数再链式调用then方法获取异步函数执行结果
6. 调用异步函数再链式调用catch方法获取异步函数执行的错误信息

```js
async function timeout() {
    console.log('我是异步函数中的代码');
    return "timeout 返回的结果"
}
console.log(timeout());

timeout().then(function (data) {
    console.log(data);
});
console.log('虽然在后面，但是我是主线程中的代码');
```

![image-20220506075956810](https://raw.githubusercontent.com/ximingx/Figurebed/master/imgs/image-20220506075956810.png)

可以看出, async 关键字定义的方法最后 return 返回的是 Promise 对象, 在函数内部没有阻塞同步代码的执行

如果要获取到promise返回值，我们应该用then方法

async 函数负责返回一个 Promise 对象，如果在async函数中 return 一个直接量，async 会把这个直接量通过Promise.resolve()  封装成 Promise 对象;如果 async 函数没有返回值,它会返回 Promise.resolve(undefined)。

## await关键字

1. **await关键字只能出现在异步函数中**
2. **await后面只能写promise对象 写其他类型的API是不不可以的**
3. await关键字可是暂停异步函数向下执行 直到promise返回结果

```js
const thenFs = require("then-fs");
async function get() {
  // throw 后, 后面的代码不执行
  throw '错误';
  let r1 =  await thenFs.readFile("./yarn.lock");
  console.log(r1.toString());
  let r2 =  await thenFs.readFile("./1.js");
  console.log(r2.toString());
  let r3 =  await thenFs.readFile("./1.html");
  console.log(r3.toString());
  return r1 + r2 + r3
}
  
    
get()
   .then(data => {
    console.log(data)
}).catch(err => {
     console.log(err)
});
```

**如果在 function 中使用了 await，则 function 必须被 async 修饰；**

async 声明了一个 异步函数，这个 异步函数 体内有一行 await 语句，它告示了该行为同步执行，并且与上下相邻的代码是依次逐行执行的。

- `async`函数执行，返回了一个 promise 对象, 不会阻塞后面的代码, 所以可以理解 task 是一个异步方法
- `await`所在的那一行语句是同步的
- **有这么一个业务需要分步完成，每个步骤都是异步的，而且依赖上一步的执行结果，甚至依赖之前每一步的结果，就可以使用Async Await来完成。**

# EventLoop

JavaScript 是一门单线程执行的编程语言。也就是说，同一时间只能做一件事情。

单线程执行任务队列的问题：如果前一个任务非常耗时，则后续的任务就不得不一直等待，从而导致程序假死的问题。

一般而言，任务分为：发出调用和得到结果两步。

- 发出调用，“立即”得到结果是为同步
- 发出调用，但无法“立即”得到结果，需要额外的操作才能得到预期的结果是为异步。

为了防止某个耗时任务导致程序假死的问题，**JavaScript 把待执行的任务分为了两类：**

- **同步任务（synchronous）**

又叫做非耗时任务，指的是在主线程上排队执行的那些任务；

- **异步任务（asynchronous）**

**又叫做耗时任务，异步任务由 JavaScript 委托给宿主环境进行执行；**
**当异步任务执行完成后，会通知 JavaScript 主线程执行异步任务的回调函数；**

**JS 执行栈采用的是后进先出的规则，当函数执行的时候，会被添加到栈的顶部，当执行栈执行完成后，就会从栈顶移出，直到栈内被清空。**

执行过程: 

- 首先任务会依次进入**执行栈**，而首先入场的就是宏任务全局上下文, 然后执行 js 主线程中的同步任务
- 将异步任务委托给宿主环境执行
- 已完成的异步任务会把它对应的回调函数放到任务队列中等待执行
- **当 js 主线程执行栈执行完毕**, 查看执行栈是否为空，如果执行栈为空
- **先检查**微任务(microTask)队列，如果存在任务，则**一次性执行完所有**微任务，无任务则跳过
- **后检查**宏任务(macroTask)队列，如果存在任务，则**取出第一个**宏任务，执行，
- 主线程不断重复上述操作

**JavaScript 主线程从“任务队列”中读取异步任务的回调函数，放到执行栈中依次执行。这个过程是循环不断的，所以整个的这种运行机制又称为 EventLoop（事件循环）。**

然而异步任务的也做了进一步的划分

1. **宏任务（macrotask）**

- 异步 Ajax 请求、
- setTimeout、setInterval、
- 文件操作
- 其它宏任务

2.  **微任务（microtask）**

- Promise.then、.catch 和 .finally
- process.nextTick
- 其它微任务

**每一个宏任务执行完之后，都会检查是否存在待执行的微任务，如果有，则执行完所有微任务之后，再继续执行下一个宏任务。**

可以简单的把宏任务认为进程, 微任务认为是线程的感觉

```js
console.log(1)
setTimeout(() => {
  console.log(2)
  new Promise(function (resolve) {
    console.log(3)
    resolve()
  }).then(() => {
    console.log(4)
  })

})

new Promise((resolve) => {
  console.log(5)
  resolve()
}).then(() => {
  console.log(6)
})

setTimeout(() => {
  console.log(7)
  new Promise(function (resolve) {
    console.log(8)
    resolve()
  }).then(() => {
    console.log(9)
  })
})

// 156234789
```



